name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run test_he.lua
      run: |
        # get slua; slua test_he.lua
        # !!no tabs!!
        uname -vm
        pwd
        wget -q -O slua https://github.com/philanc/slua/raw/master/bin/slua
        chmod ugo+x ./slua
        ./slua test_he.lua

